# Generated by Django 5.0.2 on 2024-07-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_punto', models.CharField(choices=[('Delta', 'Delta'), ('Cambio', 'Cambio')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarteraNivelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.CharField(max_length=20)),
                ('vista_mas', models.FloatField(blank=True, null=True)),
                ('vista_menos', models.FloatField(blank=True, null=True)),
                ('cota', models.FloatField(blank=True, null=True)),
                ('altura_instrumental', models.FloatField(blank=True, null=True)),
                ('basica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='top_app.basica')),
                ('tipo_punto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='top_app.tipopunto')),
            ],
        ),
    ]
