# Generated by Django 5.0.2 on 2024-07-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarteraNivelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_punto', models.CharField(choices=[('BM', 'BM'), ('Delta', 'Delta'), ('Cambio', 'Cambio')], max_length=20)),
                ('punto', models.CharField(max_length=20)),
                ('altura_instrumental', models.FloatField(blank=True, null=True)),
                ('vista_mas', models.FloatField(blank=True, null=True)),
                ('vista_menos', models.FloatField(blank=True, null=True)),
                ('cota_inicial', models.FloatField(blank=True, null=True)),
                ('cota_calculada', models.FloatField(blank=True, null=True)),
                ('basica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='top_app.informacionbasica')),
            ],
        ),
    ]
