# Generated by Django 5.0.2 on 2024-07-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='bench_mark',
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='vista_mas_inicial',
        ),
    ]
