# Generated by Django 5.0.2 on 2024-08-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0003_alter_carteranivelacion_basica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteranivelacion',
            name='basica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='top_app.informacionbasica'),
        ),
    ]
