# Generated by Django 5.0.2 on 2024-08-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0004_alter_carteranivelacion_basica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteranivelacion',
            name='basica',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='top_app.informacionbasica'),
        ),
    ]
