# Generated by Django 5.0.2 on 2024-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0005_alter_carteranivelacion_basica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteranivelacion',
            name='altura_instrumental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='cota_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='cota_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='vista_mas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='vista_menos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
