# Generated by Django 5.1.5 on 2025-02-01 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0006_alter_carteranivelacion_altura_instrumental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteranivelacion',
            name='basica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='top_app.informacionbasica'),
        ),
    ]
