# Generated by Django 5.1.5 on 2025-02-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0007_alter_carteranivelacion_basica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carteranivelacion',
            old_name='cota_calculada',
            new_name='cota',
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='cota_inicial',
        ),
    ]
