# Generated by Django 5.1.5 on 2025-02-01 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0008_rename_cota_calculada_carteranivelacion_cota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_mas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cota_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_mas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vista_menos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista_menos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='punto',
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='tipo_punto',
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='vista_mas',
        ),
        migrations.RemoveField(
            model_name='carteranivelacion',
            name='vista_menos',
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='basica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='top_app.informacionbasica'),
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_punto', models.IntegerField(choices=[(1, 'BM'), (2, 'Delta'), (3, 'Cambio')])),
                ('punto', models.CharField(max_length=20)),
                ('registro_id', models.PositiveIntegerField()),
                ('cartera_nivelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='top_app.carteranivelacion')),
            ],
        ),
    ]
