# Generated by Django 5.1.5 on 2025-02-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0009_puntobm_puntocambio_puntodelta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carteranivelacion',
            name='basica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_app.informacionbasica'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='cartera_nivelacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_app.carteranivelacion'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='tipo_punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_app.tipopunto'),
        ),
    ]
