# Generated by Django 5.1.5 on 2025-02-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0010_tipopunto_alter_carteranivelacion_basica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto', models.CharField(max_length=20)),
                ('altura_instrumental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vista_mas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vista_menos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cota_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cartera_nivelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_app.carteranivelacion')),
                ('tipo_punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top_app.tipopunto')),
            ],
        ),
        migrations.RemoveField(
            model_name='punto',
            name='cartera_nivelacion',
        ),
        migrations.RemoveField(
            model_name='punto',
            name='tipo_punto',
        ),
        migrations.DeleteModel(
            name='PuntoBM',
        ),
        migrations.DeleteModel(
            name='PuntoCambio',
        ),
        migrations.DeleteModel(
            name='PuntoDelta',
        ),
        migrations.DeleteModel(
            name='Punto',
        ),
    ]
