# Generated by Django 5.1.5 on 2025-02-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_app', '0011_puntos_remove_punto_cartera_nivelacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntos',
            old_name='cota_inicial',
            new_name='cota',
        ),
    ]
